config/routes.rb
URLShortener::Application.routes.draw do
  resources :short_urls, only: [:new, :create, :show, :index, :destroy]
  root to: "short_urls#index" # Set root to show all shortened URLs
  get "/:id", to: "short_urls#show" # Short URL redirects to long URL

  

end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base
	validates :long_url, presence: true # Validate URL to shorten isn't blank
	validate :long_url_has_scheme

	private

	def long_url_has_scheme
		unless self.long_url.include?('://') # Valid if it has a scheme
			errors[:long_url] << "must have a scheme (e.g. http://)"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  include ShortUrlsHelper

  def new
  	@short_url = ShortUrl.new
  end

  def create
  	@short_url = ShortUrl.new(long_url_param)
  	if @short_url.save
  		flash[:success] = "#{@short_url.long_url} shortened to #{url_string(@short_url)}"
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def show
  	@short_url = ShortUrl.find(params[:id])
  	redirect_to @short_url.long_url
  end

  def index
  	@short_urls = ShortUrl.all
  end

  def destroy
  	@short_url = ShortUrl.find(params[:id])
  	if @short_url.destroy
  		flash[:success] = "Deleted #{@short_url.long_url}"
  	end
  	redirect_to root_url
  end

  private
  	# strong parameters
  	def long_url_param
  		params.require(:short_url).permit(:long_url)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
	# Create url from ShortUrl object without protocol
	def url_string(short_url)
		"#{request.host_with_port}/#{short_url.id}"
	end

	# Create full url from ShortUrl object with protocol
	def full_url_string(short_url)
		"#{request.protocol}#{url_string(short_url)}"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>URLShortener</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>

	<%= yield %>

</body>
</html>

app/views/short_urls/index.html.erb
<h1>Shortened URLs</h1>

<p>
	<%= button_to new_short_url_path, method: :get do %>
		Shorten a new URL
	<% end %>
</p>

<table border="1" cellpadding="10">
	<th></th>
	<th>Shortened URL</th>
	<th>Original URL</th>
	<% if @short_urls.any? %>
		<% @short_urls.each do |short_url| %>
			<tr>
				<td>
					<%= button_to short_url, method: :delete, data: { confirm: "Are you sure?" } do %>
						delete
					<% end %>
				</td>

				<% long_url_string = short_url.long_url %>
				<td><%= link_to url_string(short_url), full_url_string(short_url) %></td>
				<td><%= link_to long_url_string, long_url_string %></td>
			</tr>
		<% end %>
	<% else %>
		<tr><td></td><td>none</td><td></td></tr>
	<% end %>
</table>

app/views/short_urls/new.html.erb
<h1>Shorten a New URL</h1>

<%= form_for @short_url do |f| %>
	<% if @short_url.errors.any? %>
		<ul>
			<% @short_url.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :long_url, "URL" %>
		<%= f.text_field :long_url, value: "http://", size: 50  %>
	</p>

	<p><%= f.submit "Shorten" %></p>
<% end %>